### ISSUE TITLE
Freeze with logging to stdout

### ISSUE THREAD

**Issue by styks90** [fauria/docker-vsftpd#30]
We have a docker-compose file that includes the fauria/vsftpd image:

```
vsftpd:
    image: fauria/vsftpd
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    volumes:
      - ./data/:/home/vsftpd/
    environment:
      - "FTP_USER=user"
      - "FTP_PASS=pass"
      - "PASV_ADDRESS=ftp"
      - "PASV_MIN_PORT=21100"
      - "PASV_MAX_PORT=21110"
      # - "LOG_STDOUT=YES"
```

However, the build freezes when we try to log the output to STDOUT. Is this a known issue, or did we configure it wrong?
