### ISSUE TITLE
How to properly mount and structure the Volume

### ISSUE THREAD

**Issue by CpBobette** [fauria/docker-vsftpd#54]
Hi,

I feel like I am missing something obvious, I created the directory and changed the ownership to user 14 and group 50 but I keep getting errors when listing the directory.

**Comment by salprima** [comment]
Me too getting the same issue as @CpBobette below is my docker-compose file for the reference

```
version: '3.7'
services:
  ftpd_docker:
    image: fauria/vsftpd
    container_name: ftpd_docker
    environment:
      FTP_USER: foo
      FTP_PASS: bar
      PASV_ADDRESS_ENABLE: "YES"
      PASV_ADDRESS: 127.0.0.1
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 21100-21110:21100-21110
    volumes:
      - ./data/vsftpd:/home/vsftpd
      - ./data/log:/var/log/vsftpd
```

the home directory is created under `./data/vsftpd/foo` but the directory listing still failed at some point. I'm running on `MacOD Catalina 10.15.6` any clue will be appreciated
