### ISSUE TITLE
No files available

### ISSUE THREAD

**Issue by Bence98007** [fauria/docker-vsftpd#68]
Hi there!
Thanks for the effort creating a lightweight ftp docker image!

I just missing something, maybe permission issues?
So I created a compose file, which is the following:
```
version: '3.3'
services:
    vsftpd:
        volumes:
            - /var/containersdata/ftp-srv/data:/home/vsftpd
            - /var/containersdata/ftp-srv/log:/var/log/vsftpd
        ports:
            - '20:20'
            - '21:21'
            - '21100-21110:21100-21110'
        environment:
            - FTP_USER=user
            - FTP_PASS=pass
            - PASV_MIN_PORT=21100
            - PASV_MAX_PORT=21110
            - LOCAL_UMASK=0777
        container_name: ftp-srv
        restart: always
        image: fauria/vsftpd
```

But as I connect to the FTP server from my network (so no firewall etc) the connection is up, but I can see no files there.
I tried to create a symlink to the ftp-shared folder, and also just a txt file, but no success, nothing is shown in my ftp server.
What am I doing wrong?
