### ISSUE TITLE
Delaying before reconnect

### ISSUE THREAD

**Issue by MaxG87** [fauria/docker-vsftpd#84]
I try to use this container to get a local FTP server for testing purposes. Unfortunately, I cannot get it to work.

My `docker-compose.yml` is:

```
version: "3.7"

services:
  ftp:
    image: fauria/vsftpd:latest
    container_name: vsftpd-compose
    restart: always
    environment:
      - FTP_USER=admin
      - FTP_PASS=passwd
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - LOG_STDOUT=yes
    ports:
      - 20:20
      - 21:21
      - "21100-21110:21100-21110"
```

I try to connect to this via `LANG= lftp "localhost" -p 21100 -u admin,passwd`. Once I issue the first command, e.g. `ls` or `PUT file`, I get an error message: `Delaying before reconnect`.

I couldn't find anything helpful in the internet. I only found #1 , but couldn't understand if there was a resolution for that. Is anything known here? Any help would be appreciated.
