### ISSUE TITLE
Unable to connect with latest image from Filezilla client

### ISSUE THREAD

**Issue by DanTurco** [fauria/docker-vsftpd#88]
Its like its forcing SSL, and no logs are generated

Docker.compose
```yaml
  vsftp:
    container_name: vsftp
    image: "fauria/vsftpd"
    restart: always
    ports:
        - 0.0.0.0:20:20
        - 0.0.0.0:21:21
        - "21100-21110:21100-21110"
    environment:
      - FTP_USER=admin
      - FTP_PASS=PassW0rd!
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
    volumes:
        - vol_ftp:/home/vsftpd
        - vol_ftp:/var/log/vsftpd
```

Logs
![image](https://github.com/fauria/docker-vsftpd/assets/147526328/9c136ab6-b230-46c8-8cd3-a3f31799f8fd)

Filezilla Site
![image](https://github.com/fauria/docker-vsftpd/assets/147526328/ab0f4e30-8156-4ea8-876a-e904a1623d80)

Filezilla output
```text
Response:	220 (vsFTPd 3.0.2)
Command:	AUTH TLS
Response:	530 Please login with USER and PASS.
Command:	AUTH SSL
Response:	530 Please login with USER and PASS.
Status:	Insecure server, it does not support FTP over TLS.
Command:	USER cbxuser
Response:	331 Please specify the password.
Command:	PASS *********
Error:	Connection timed out after 20 seconds of inactivity
Error:	Could not connect to server
```
